### ISSUE TITLE
remove flutter dependency

### ISSUE THREAD

**Issue by zoechi** [jrnelson333/flutter_rx#1]
I was curious about this package because it claims to be inspired by NgRx,
but I want to build my state in a Dart package, that doesn't depend on Flutter.
This state package should be imported by the Flutter app package, but not depend on Flutter itself.
I'd prefer the state and the Flutter part to be 2 separate packages where only the later depends on Flutter if there is some actual integration (similar to https://pub.dev/packages/flutter_redux)

Would you consider such a change?

**Comment by Jordan-Nelson** [comment]
Hi @zoechi - Yeah, I had actually thought about doing that, but never really had a need since I am only using it in flutter apps. It should be pretty straight forward to split this into two packages - one with everything that doesn't depend on flutter, and one with the StoreProvider and StoreConnector widgets.

If you are interested in opening a PR, feel free. Otherwise I could look into doing it next week.

Not sure about naming for the new non-flutter package. Let me know if you have thoughts.

**Comment by zoechi** [comment]
Hi @Jordan-Nelson thanks for your response and explaining your plans and ideas.
I don't think I'll be able to do a PR short term.
Naming is hard here, because "rx" is used a lot.
My suggestion would be "dart_rx".

**Comment by Jordan-Nelson** [comment]
@zoechi - A first draft of the separated lib is in the branch [feat/dart-refactor](https://github.com/Jordan-Nelson/flutter_rx/tree/feat/dart-refactor). Still haven't landed on what to call the dart lib. For now I have named it `flutter_rx_core`.

**Comment by zoechi** [comment]
Great :)
The name makes sense. 
I'm eager to try it out but I won't be on my computer for several days.

**Comment by Jordan-Nelson** [comment]
@zoechi - The initial version of `flutter_rx_core` has been published, along with a new version of `flutter_rx`.

`flutter_rx_core` is pretty bare bones. I did not add an example or much to the readme. I may do that later. The `flutter_rx` readme is up to date though and generally everything applies to the core lib as well, minus the `StoreProvider` and `StoreConnector` widgets.

https://pub.dev/packages/flutter_rx
https://pub.dev/packages/flutter_rx_core

**Comment by zoechi** [comment]
@Jordan-Nelson thanks a lot! I hope I'll be able to try it soon.
